services:
  microshoppingservice.auth.api:
    image: ${DOCKER_REGISTRY-}microshoppingserviceauthapi
    build:
      context: .
      dockerfile: MicroShoppingService.Auth.API/Dockerfile
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authdb;Username=postgres;Password=your_password
    networks:
      - app-network

  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
      
volumes:
  postgres-data:

networks:
  app-network: